[[containers]]

token = ""
count = 3
ephemeral = true
platform = "linux/arm64"

  [containers.repository]

  name = ""
  owner = ""

  [[containers.volumes]]

  hostPath = "/home/ubuntu/.cache"
  containerPath = "/home/ubuntu/.cache"

